# Generated by Django 5.0 on 2024-04-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=14)),
                ('instrument_type', models.CharField(choices=[('Guitar', 'Guitar'), ('Bass', 'Bass'), ('Drums', 'Drums'), ('Trumpet', 'Trumpet'), ('Piano', 'Piano'), ('Violin', 'Violin'), ('Saxophone', 'Saxophone'), ('Flute', 'Flute'), ('Harp', 'Harp'), ('Cello', 'Cello')], max_length=10)),
            ],
        ),
    ]
