# Generated by Django 5.0 on 2024-05-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_mainmodel_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainmodel',
            old_name='img',
            new_name='pro_img',
        ),
        migrations.AddField(
            model_name='mainmodel',
            name='app_img',
            field=models.ImageField(blank=True, upload_to='mainApp/media/uploads/'),
        ),
    ]
