# Generated by Django 5.0 on 2024-05-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_rename_img_mainmodel_pro_img_mainmodel_app_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmodel',
            name='app_img',
            field=models.ImageField(blank=True, upload_to='mainApp/media/'),
        ),
        migrations.AlterField(
            model_name='mainmodel',
            name='pro_img',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
