# Generated by Django 5.0 on 2024-05-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_mainmodel_app_img_alter_mainmodel_pro_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainmodel',
            old_name='app_img',
            new_name='dp',
        ),
        migrations.RemoveField(
            model_name='mainmodel',
            name='pro_img',
        ),
    ]
