# Generated by Django 5.0 on 2024-05-09 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_rename_app_img_mainmodel_dp_remove_mainmodel_pro_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainmodel',
            old_name='dp',
            new_name='img',
        ),
    ]
