# Generated by Django 5.0 on 2024-05-09 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_rename_dp_mainmodel_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainmodel',
            old_name='img',
            new_name='pic',
        ),
    ]
