# Generated by Django 5.0 on 2024-05-09 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_extramodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extramodel',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mainApp.mainmodel'),
        ),
    ]
