# Generated by Django 5.0 on 2024-05-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='myModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(blank=True)),
                ('email_address', models.EmailField(max_length=254, null=True)),
                ('cgpa', models.FloatField(verbose_name='CGPA')),
                ('checkbox', models.BooleanField(default=False)),
                ('profile', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mytable',
            name='address',
        ),
        migrations.RemoveField(
            model_name='mytable',
            name='email',
        ),
    ]
