# Generated by Django 5.0 on 2024-05-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4models', '0003_alter_mymodel_email_address_alter_mymodel_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='profile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
