# Generated by Django 5.0 on 2024-05-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4models', '0004_alter_mymodel_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='profile',
            field=models.URLField(null=True),
        ),
    ]
