# Generated by Django 5.0 on 2024-05-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4models', '0005_alter_mymodel_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='full_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
