# Generated by Django 5.0 on 2024-05-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4models', '0006_alter_mymodel_full_name_alter_mymodel_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
