# Generated by Django 5.0 on 2024-05-05 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4models', '0007_mymodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='slug',
        ),
    ]
