# Generated by Django 5.0 on 2024-05-02 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app4models', '0006_alter_mymodel_full_name_alter_mymodel_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='exampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='relationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app4models.mymodel')),
                ('category', models.ManyToManyField(related_name='category', to='app4models.mytable')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app4relations.examplemodel')),
            ],
        ),
    ]
