# Generated by Django 5.0 on 2024-05-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4relations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
