# Generated by Django 5.0 on 2024-04-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelFields', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='date_field',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='duration_field',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='email_field',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='time_field',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='student',
            name='father_name',
        ),
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='url_field',
            field=models.URLField(default='http://phitron.io/'),
        ),
    ]
